### ISSUE TITLE
Error with custom datasets

### ISSUE THREAD

**Issue by cv-lab-x** [turandai/gaussian_surfels#16]
hi, thanks for your great work, some errors when train with custom datasets

`Loading cameras: 3500 for training and 500 for testing
Number of points at initialisation :  1269404
Training progress:   0%|                                                                                                                                                            | 0/40000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "gaussian_surfels/train.py", line 300, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "gaussian_surfels/train.py", line 145, in training
    loss.backward()
  File "conda_envs/envs/surfel_gs/lib/python3.10/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "conda_envs/envs/surfel_gs/lib/python3.10/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Function _RasterizeGaussiansBackward returned an invalid gradient at index 2 - got [0, 0, 3] but expected shape compatible with [0, 16, 3]
`
@turandai Looking forward to your reply, thanks.

**Comment by cv-lab-x** [comment]
> Hi, I think this might be similar to [this](https://github.com/turandai/gaussian_surfels/issues/10#issuecomment-2097864224), please checkout.

thanks for your quick reply.
